export const hardCodedOperationData = {
  data: [
    {
      parent: null,
      source_id: null,
      id: 2,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 0,
      res_line_id: 0,
      operation_type: 'project',
      task_type: 'project',
      work_center_id: '',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: '0',
      planned_resource_name: '',
      operation_number: 0,
      operation_code: 'WO00000021',
      description: 'WO00000021',
      priority: '99',
      readonly: 0,
      status: '0',
      start_date: '2022-01-21T12:00:00',
      end_date: '2022-03-21T00:00:00',
      duration: 0,
      min_duration: 0,
      progress: 0,
      is_local_task: null,
      is_deleted: null,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 0,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
    {
      parent: 2,
      source_id: 2,
      id: 19,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 1,
      res_line_id: 0,
      operation_type: 'project',
      task_type: 'operation',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 8,
      resource_name: 'machine type',
      planned_resource_id: '',
      planned_resource_name: '',
      operation_number: 1,
      operation_code: 'SM-Sub/contracting',
      description: '\\subcontracting|?/',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T19:00:00',
      end_date: '2022-01-23T16:00:00',
      duration: 32,
      min_duration: 32,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
    {
      parent: 19,
      source_id: null,
      id: 74,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 1,
      res_line_id: 1,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'SM-SUb2',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: 'SM-SUb2',
      planned_resource_name: '',
      operation_number: 1,
      operation_code: 'labour type',
      description: '\\subcontracting|?/',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T09:00:00',
      end_date: '2022-01-21T10:00:00',
      duration: 1,
      min_duration: 1,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 2,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 1,
      OPTM_ROU_CONS_TUOM: 1,
      OPTM_TIME_UOM: null,
    },
    {
      parent: 19,
      source_id: null,
      id: 75,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 1,
      res_line_id: 2,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'Sm-rmd-machine',
      res_id: 8,
      resource_name: 'machine type',
      planned_resource_id: 'Sm-rmd-machine',
      planned_resource_name: 'machine type',
      operation_number: 1,
      operation_code: 'machine type',
      description: '\\subcontracting|?/',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T19:00:00',
      end_date: '2022-01-21T21:00:00',
      duration: 50,
      min_duration: 50,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 10,
      OPTM_ROU_CONS_TUOM: 50,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: 19,
      source_id: null,
      id: 76,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 1,
      res_line_id: 3,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'SM-rmd-labour',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: 'SM-rmd-labour',
      planned_resource_name: 'labour type',
      operation_number: 1,
      operation_code: 'labour type',
      description: '\\subcontracting|?/',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T19:00:00',
      end_date: '2022-01-21T18:00:00',
      duration: 32,
      min_duration: 32,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 5,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 12,
      OPTM_ROU_CONS_TUOM: 32,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: '2',
      source_id: 21,
      id: 20,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 2,
      res_line_id: 0,
      operation_type: 'project',
      task_type: 'operation',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: '',
      planned_resource_name: '',
      operation_number: 2,
      operation_code: 'SM-OM-Setup',
      description: 'Setup operation',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T12:00:00',
      end_date: '2022-01-21T18:00:00',
      duration: 750,
      min_duration: 750,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
    {
      parent: '21',
      source_id: 20,
      id: 77,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 2,
      res_line_id: 4,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'SM-rmd-labour',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: 'SM-rmd-labour',
      planned_resource_name: 'labour type',
      operation_number: 2,
      operation_code: 'labour type',
      description: 'Setup operation',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T12:00:00',
      end_date: '2022-01-21T14:40:00',
      duration: 266.667,
      min_duration: 266.667,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 5,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 100,
      OPTM_ROU_CONS_TUOM: 266.667,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: '21',
      source_id: 20,
      id: 78,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 2,
      res_line_id: 5,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'Sm-rmd-machine',
      res_id: 8,
      resource_name: 'machine type',
      planned_resource_id: 'Sm-rmd-machine',
      planned_resource_name: 'machine type',
      operation_number: 2,
      operation_code: 'machine type',
      description: 'Setup operation',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T12:00:00',
      end_date: '2022-01-25T18:00:00',
      duration: 750,
      min_duration: 750,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 150,
      OPTM_ROU_CONS_TUOM: 750,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: '2',
      source_id: 2,
      id: 21,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 3,
      res_line_id: 0,
      operation_type: 'project',
      task_type: 'operation',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: '',
      planned_resource_name: '',
      operation_number: 3,
      operation_code: 'SM-MANU',
      description: 'manufactuirng',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T18:00:00',
      end_date: '2022-03-01T00:00:00',
      duration: 376,
      min_duration: 376,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
    {
      parent: '21',
      source_id: 21,
      id: 79,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 3,
      res_line_id: 6,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'Sm-rmd-machine',
      res_id: 8,
      resource_name: 'machine type',
      planned_resource_id: 'Sm-rmd-machine',
      planned_resource_name: 'machine type',
      operation_number: 3,
      operation_code: 'machine type',
      description: 'manufactuirng',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T18:00:00',
      end_date: '2022-02-20T04:00:00',
      duration: 610,
      min_duration: 610,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 122,
      OPTM_ROU_CONS_TUOM: 610,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: '21',
      source_id: 21,
      id: 80,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 3,
      res_line_id: 7,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'SM-rmd-labour',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: 'SM-rmd-labour',
      planned_resource_name: 'labour type',
      operation_number: 3,
      operation_code: 'labour type',
      description: 'manufactuirng',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T18:00:00',
      end_date: '2022-02-28T20:00:00',
      duration: 376,
      min_duration: 376,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 5,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 141,
      OPTM_ROU_CONS_TUOM: 376,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: 21,
      source_id: 21,
      id: 163,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 3,
      res_line_id: 0,
      operation_type: 'task',
      task_type: 'move',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 8,
      resource_name: 'machine type',
      planned_resource_id: '',
      planned_resource_name: '',
      operation_number: 3,
      operation_code: 'Move',
      description: 'manufactuirng',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T20:00:00',
      end_date: '2022-03-01T00:00:00',
      duration: 0,
      min_duration: 0,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
  ],
  links: [
    {
      parent: null,
      source: 2,
      target: 19,
      id: 2,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 0,
      res_line_id: 0,
      operation_type: 'project',
      task_type: 'project',
      work_center_id: '',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 7,
      resource_name: '',
      planned_resource_id: '0',
      planned_resource_name: '',
      operation_number: 0,
      operation_code: 'WO00000021',
      description: 'WO00000021',
      priority: '99',
      readonly: 0,
      status: '0',
      start_date: '2022-01-21T12:00:00',
      end_date: '2022-03-01T00:00:00',
      duration: 0,
      min_duration: 0,
      progress: 0,
      is_local_task: null,
      is_deleted: null,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 0,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
    {
      parent: 2,
      source: 19,
      target: 21,
      id: 19,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 1,
      res_line_id: 0,
      operation_type: 'project',
      task_type: 'operation',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 8,
      resource_name: '',
      planned_resource_id: '',
      planned_resource_name: '',
      operation_number: 1,
      operation_code: 'SM-Sub/contracting',
      description: '\\subcontracting|?/',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T19:00:00',
      end_date: '2022-01-25T16:00:00',
      duration: 32,
      min_duration: 32,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
    {
      parent: 19,
      source_id: null,
      id: 74,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 1,
      res_line_id: 1,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'SM-SUb2',
      res_id: 7,
      resource_name: '',
      planned_resource_id: 'SM-SUb2',
      planned_resource_name: '',
      operation_number: 1,
      operation_code: '',
      description: '\\subcontracting|?/',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T09:00:00',
      end_date: '2022-01-21T10:00:00',
      duration: 1,
      min_duration: 1,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 2,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 1,
      OPTM_ROU_CONS_TUOM: 1,
      OPTM_TIME_UOM: null,
    },
    {
      parent: 19,
      source_id: null,
      id: 75,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 1,
      res_line_id: 2,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'Sm-rmd-machine',
      res_id: 8,
      resource_name: 'machine type',
      planned_resource_id: 'Sm-rmd-machine',
      planned_resource_name: 'machine type',
      operation_number: 1,
      operation_code: 'machine type',
      description: '\\subcontracting|?/',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T19:00:00',
      end_date: '2022-01-24T21:00:00',
      duration: 50,
      min_duration: 50,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 10,
      OPTM_ROU_CONS_TUOM: 50,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: 19,
      source_id: null,
      id: 76,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 1,
      res_line_id: 3,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'SM-rmd-labour',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: 'SM-rmd-labour',
      planned_resource_name: 'labour type',
      operation_number: 1,
      operation_code: 'labour type',
      description: '\\subcontracting|?/',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T19:00:00',
      end_date: '2022-01-25T18:00:00',
      duration: 32,
      min_duration: 32,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 5,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 12,
      OPTM_ROU_CONS_TUOM: 32,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: 2,
      source_id: 21,
      id: 20,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 2,
      res_line_id: 0,
      operation_type: 'project',
      task_type: 'operation',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 8,
      resource_name: '',
      planned_resource_id: '',
      planned_resource_name: '',
      operation_number: 2,
      operation_code: 'SM-OM-Setup',
      description: 'Setup operation',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T12:00:00',
      end_date: '2022-01-21T18:00:00',
      duration: 750,
      min_duration: 750,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
    {
      parent: 20,
      source_id: 20,
      id: 77,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 2,
      res_line_id: 4,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'SM-rmd-labour',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: 'SM-rmd-labour',
      planned_resource_name: 'labour type',
      operation_number: 2,
      operation_code: 'labour type',
      description: 'Setup operation',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T12:00:00',
      end_date: '2022-01-25T14:40:00',
      duration: 266.667,
      min_duration: 266.667,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 5,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 100,
      OPTM_ROU_CONS_TUOM: 266.667,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: 20,
      source_id: 20,
      id: 78,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 2,
      res_line_id: 5,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'Sm-rmd-machine',
      res_id: 8,
      resource_name: 'machine type',
      planned_resource_id: 'Sm-rmd-machine',
      planned_resource_name: 'machine type',
      operation_number: 2,
      operation_code: 'machine type',
      description: 'Setup operation',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T12:00:00',
      end_date: '2022-01-21T18:00:00',
      duration: 750,
      min_duration: 750,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 150,
      OPTM_ROU_CONS_TUOM: 750,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: 2,
      source_id: 19,
      id: 21,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 3,
      res_line_id: 0,
      operation_type: 'project',
      task_type: 'operation',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 7,
      resource_name: '',
      planned_resource_id: '',
      planned_resource_name: '',
      operation_number: 3,
      operation_code: 'SM-MANU',
      description: 'manufactuirng',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T18:00:00',
      end_date: '2022-03-01T00:00:00',
      duration: 376,
      min_duration: 376,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
    {
      parent: 21,
      source_id: 21,
      id: 79,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 3,
      res_line_id: 6,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'Sm-rmd-machine',
      res_id: 8,
      resource_name: 'machine type',
      planned_resource_id: 'Sm-rmd-machine',
      planned_resource_name: 'machine type',
      operation_number: 3,
      operation_code: 'machine type',
      description: 'manufactuirng',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T18:00:00',
      end_date: '2022-02-20T04:00:00',
      duration: 610,
      min_duration: 610,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 122,
      OPTM_ROU_CONS_TUOM: 610,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: 21,
      source_id: 21,
      id: 80,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 3,
      res_line_id: 7,
      operation_type: 'task',
      task_type: 'resource',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: 'SM-rmd-labour',
      res_id: 7,
      resource_name: 'labour type',
      planned_resource_id: 'SM-rmd-labour',
      planned_resource_name: 'labour type',
      operation_number: 3,
      operation_code: 'labour type',
      description: 'manufactuirng',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T18:00:00',
      end_date: '2022-02-28T20:00:00',
      duration: 376,
      min_duration: 376,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 1,
      CAL_ID: 5,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 141,
      OPTM_ROU_CONS_TUOM: 376,
      OPTM_TIME_UOM: 'Hours',
    },
    {
      parent: '2',
      source_id: 21,
      id: 163,
      ref_id: 73,
      head_doc_entry: 21,
      oper_doc_entry: 21,
      oper_line_id: 3,
      res_line_id: 0,
      operation_type: 'task',
      task_type: 'move',
      work_center_id: 'SM-WC',
      work_order_id: 'WO00000021',
      RESOURCE_ID: '0',
      res_id: 8,
      resource_name: '',
      planned_resource_id: '',
      planned_resource_name: '',
      operation_number: 3,
      operation_code: 'Move',
      description: 'manufactuirng',
      priority: '99',
      readonly: 0,
      status: '2',
      start_date: '2022-01-21T20:00:00',
      end_date: '2022-03-01T00:00:00',
      duration: 0,
      min_duration: 0,
      progress: 0,
      is_local_task: 0,
      is_deleted: 0,
      split_task_grp_id: 0,
      required_resource: 0,
      CAL_ID: 0,
      WC_CAL_ID: 7,
      OPTM_ROU_CONS_RUOM: 0,
      OPTM_ROU_CONS_TUOM: 0,
      OPTM_TIME_UOM: '',
    },
  ],
};

export const hardCodedResoucesData = {
  OUTPUT: [
    {
      ErrNumber: '0',
      ErrCode: 'No_Error',
      ErrSrcFile: '',
      ErrSrcFn: '',
      ErrDesc: '',
      RESULT: '',
      ParamVals: '',
      Data: '',
    },
  ],
  Resources: [
    {
      work_center_id: 'SM-WC',
      RESOURCE_ID: 'SM-rmd-labour',
      name: 'labour type',
      id: 7,
      CAL_ID: 5,
      start_date: '2022-01-21T00:00:00',
      end_date: '2022-01-21T18:00:00',
    },
    {
      work_center_id: 'SM-WC',
      RESOURCE_ID: 'Sm-rmd-machine',
      name: 'machine type',
      id: 8,
      res_id: 8,
      CAL_ID: 0,
      start_date: '2022-01-21T00:00:00',
      end_date: '2022-01-21T06:00:00',
    },
  ],
  Capacity: [
    {
      work_center_id: 'SM-WC',
      RESOURCE_ID: 'SM-rmd-machine',
      id: 8,
      name: 'machine type',
      workdate: '2022-01-21T00:00:00',
      WK: '04-2022',
      MTH: '01-2022',
      YR: 2021,
      avail_capacity: 120,
      week_capacity: 48,
      mth_capacity: 88,
      yr_capacity: 88,
    },
    {
      work_center_id: 'SM-WC',
      RESOURCE_ID: 'SM-rmd-labour',
      id: 7,
      name: 'labour type',
      workdate: '2022-01-21T00:00:00',
      WK: '04-2022',
      MTH: '01-2022',
      YR: 2021,
      avail_capacity: 120,
      week_capacity: 48,
      mth_capacity: 88,
      yr_capacity: 88,
    },
  ],
  TaskType: [
    {
      KEY: 1,
      LABEL: 'Setup',
      UNIQUE_NAME: 'setup',
    },
    {
      KEY: 2,
      LABEL: 'Operation',
      UNIQUE_NAME: 'operation',
    },
    {
      KEY: 3,
      LABEL: 'Interruption',
      UNIQUE_NAME: 'interruption',
    },
    {
      KEY: 4,
      LABEL: 'Overload',
      UNIQUE_NAME: 'overload',
    },
    {
      KEY: 5,
      LABEL: 'Breakdown',
      UNIQUE_NAME: 'breakdown',
    },
    {
      KEY: 6,
      LABEL: 'Maintenance',
      UNIQUE_NAME: 'maintenance',
    },
    {
      KEY: 7,
      LABEL: 'Lunch Break',
      UNIQUE_NAME: 'lunch_break',
    },
    {
      KEY: 8,
      LABEL: 'Machine Down',
      UNIQUE_NAME: 'machine_down',
    },
    {
      KEY: 9,
      LABEL: 'Power Cut',
      UNIQUE_NAME: 'power_cut',
    },
    {
      KEY: 10,
      LABEL: 'Resource',
      UNIQUE_NAME: 'resource',
    },
  ],
  Priority: [
    {
      CODE: '1',
      MIN_VALUE: '1',
      MAX_VALUE: '10',
      RANGE: '1-10',
      DESCRIPTION: 'High',
    },
    {
      CODE: '11',
      MIN_VALUE: '11',
      MAX_VALUE: '30',
      RANGE: '11-30',
      DESCRIPTION: 'Medium',
    },
    {
      CODE: '31',
      MIN_VALUE: '31',
      MAX_VALUE: '99',
      RANGE: '31-99',
      DESCRIPTION: 'Low',
    },
  ],
  Workcenters: [
    {
      U_O_WC_ID: 'CK-WCM',
      id: 'CK-WCM',
      name: 'WCM',
    },
    {
      U_O_WC_ID: 'WC 1',
      id: 'WC 1',
      name: 'first work center',
    },
    {
      U_O_WC_ID: 'SM-WC',
      id: 'SM-WC',
      name: 'sarthak',
    },
  ],
  WorkOrders: [
    {
      work_order_number: 'WO00000016',
    },
    {
      work_order_number: 'WO00000021',
    },
    {
      work_order_number: 'WO00000050',
    },
    {
      work_order_number: 'WO00000068',
    },
    {
      work_order_number: 'WO00000081',
    },
    {
      work_order_number: 'WO00000097',
    },
    {
      work_order_number: 'WO00000021',
    },
    {
      work_order_number: 'WO00000026',
    },
    {
      work_order_number: 'WO00000050',
    },
    {
      work_order_number: 'WO00000068',
    },
    {
      work_order_number: 'WO00000081',
    },
    {
      work_order_number: 'WO00000097',
    },
    {
      work_order_number: 'WO00000099',
    },
    {
      work_order_number: 'WO00000119',
    },
    {
      work_order_number: 'WO00000134',
    },
    {
      work_order_number: 'WO00000155',
    },
    {
      work_order_number: 'WO00000156',
    },
    {
      work_order_number: 'WO00000183',
    },
    {
      work_order_number: 'WO00000188',
    },
    {
      work_order_number: 'WO00000189',
    },
    {
      work_order_number: 'WO00000021',
    },
    {
      work_order_number: 'WO00000021',
    },
    {
      work_order_number: 'WO00000026',
    },
    {
      work_order_number: 'WO00000026',
    },
    {
      work_order_number: 'WO00000050',
    },
    {
      work_order_number: 'WO00000050',
    },
    {
      work_order_number: 'WO00000068',
    },
    {
      work_order_number: 'WO00000068',
    },
    {
      work_order_number: 'WO00000068',
    },
    {
      work_order_number: 'WO00000068',
    },
    {
      work_order_number: 'WO00000068',
    },
    {
      work_order_number: 'WO00000081',
    },
    {
      work_order_number: 'WO00000081',
    },
    {
      work_order_number: 'WO00000097',
    },
    {
      work_order_number: 'WO00000097',
    },
    {
      work_order_number: 'WO00000099',
    },
    {
      work_order_number: 'WO00000099',
    },
    {
      work_order_number: 'WO00000119',
    },
    {
      work_order_number: 'WO00000134',
    },
    {
      work_order_number: 'WO00000134',
    },
    {
      work_order_number: 'WO00000155',
    },
    {
      work_order_number: 'WO00000155',
    },
    {
      work_order_number: 'WO00000155',
    },
    {
      work_order_number: 'WO00000155',
    },
    {
      work_order_number: 'WO00000183',
    },
    {
      work_order_number: 'WO00000188',
    },
    {
      work_order_number: 'WO00000188',
    },
    {
      work_order_number: 'WO00000188',
    },
    {
      work_order_number: 'WO00000188',
    },
    {
      work_order_number: 'WO00000189',
    },
    {
      work_order_number: 'WO00000189',
    },
    {
      work_order_number: 'WO00000189',
    },
    {
      work_order_number: 'WO00000189',
    },
    {
      work_order_number: 'WO00000026',
    },
  ],
};
